# Generated by Django 4.2.11 on 2024-04-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField()),
                ('name', models.CharField()),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField()),
                ('name', models.CharField()),
                ('summary', models.TextField()),
                ('rating', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True)),
                ('status', models.CharField(choices=[('1', 'Not started'), ('2', 'In progress'), ('3', 'Finished'), ('4', 'Dropped'), ('5', 'Taking a break'), ('6', 'Playing again!')], default='1')),
            ],
        ),
    ]
