# Generated by Django 4.2.11 on 2024-04-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_game_cover_usergame_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.TextField(default='https://pbs.twimg.com/media/EfTsvxKXsAALmnb.jpg:large'),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='cover',
            field=models.TextField(default='https://pbs.twimg.com/media/EfTsvxKXsAALmnb.jpg:large'),
        ),
    ]
