# Generated by Django 4.2.11 on 2024-04-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_game_cover_alter_usergame_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.TextField(default='https://i.pinimg.com/736x/64/9d/37/649d37014bd486376f3f8552a1f049d8.jpg'),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='cover',
            field=models.TextField(default='https://i.pinimg.com/736x/64/9d/37/649d37014bd486376f3f8552a1f049d8.jpg'),
        ),
    ]
