# Generated by Django 4.2.11 on 2024-04-30 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user_game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.usergame'),
            preserve_default=False,
        ),
    ]
